/* eslint-disable import/no-anonymous-default-export */
export default {
    name:"Ali Bolouri",
    home:"HOME",
    contact:"CONTACT",
    resume:"RESUME",
    about:"ABOUT",
    por:"PORTOFOLIOS",
    hi:"Hi, I am ",
    hi2:"",
    des:"I am fontend web developer.I can provide clean code and perfect pixel design.I also make website more & more interactive with web animations.",
    aboutme:"ABOUT ME",
    services:"SERVICES",
    nationality:"Nationality",
    languages:"Languages",
    phone:"Phone",
    age:"Age",
    iran:"Iran",
    persian:"Persian",
    english:"English",
    years:"Years",
    fullname:"FullName",
    download:"download cv",
    webdesign:"Web Design",
    webdevelopment:"Web Development",
    machinelearning:"Machine Learning",
    servicedesc:"Incidunt vitae quae facere ducimus nostrum aliquid dolorum veritatis dicta!",
    skill:"SKILLS",
    aboutresume:"RESUME",
     work: [
        { id: 0, date: "", title: "", subtitle: "", content: "" },
        { id: 1, date: "2019-2020", title: "Frontend Developer", subtitle: "Zarinpal", content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book." },
        { id: 2, date: "2020-2021", title: "Backend Developer", subtitle: "Snapp", content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book." },
        { id: -1, date: "", title: "", subtitle: "", content: "" },
    ],
    school: [
        { id: 0, date: "", title: "", subtitle: "", content: "" },
        { id: 1, date: "2019-2020", title: "University", subtitle: "Science & Research", content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book." },
        { id: 2, date: "2020-2021", title: "High School", subtitle: "khayam", content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book." },
        { id: -1, date: "", title: "", subtitle: "", content: "" },
    ],
    education:"Educational Background",
    workExp:"Work Experience",
    contactme:"CONTACT ME",
    namecontact:"Enter your name",
    emailcontact:"Enter your email",
    subjectcontact:"Enter your subject",
    messagecontact:"Enter your message",
    sendmessage:"send message",
    getintouch:"Get In Touch",
    portofolioList: [
        { id: 0, title: "React Project", desc: "Incidunt vitae quae facere ducimus nostrum aliquid dolorum veritatis dicta!", image: "https://i.pinimg.com/236x/fc/31/8d/fc318d62be7b3c903a1feb10bd8d6704.jpg" },
        { id: 1, title: "React Project", desc: "Incidunt vitae quae facere ducimus nostrum aliquid dolorum veritatis dicta!", image: "https://i.pinimg.com/236x/fc/31/8d/fc318d62be7b3c903a1feb10bd8d6704.jpg" },
        { id: 2, title: "React Project", desc: "Incidunt vitae quae facere ducimus nostrum aliquid dolorum veritatis dicta!", image: "https://i.pinimg.com/236x/fc/31/8d/fc318d62be7b3c903a1feb10bd8d6704.jpg" },
        { id: 3, title: "React Project", desc: "Incidunt vitae quae facere ducimus nostrum aliquid dolorum veritatis dicta!", image: "https://i.pinimg.com/236x/fc/31/8d/fc318d62be7b3c903a1feb10bd8d6704.jpg" },
        { id: 4, title: "React Project", desc: "Incidunt vitae quae facere ducimus nostrum aliquid dolorum veritatis dicta!", image: "https://i.pinimg.com/236x/fc/31/8d/fc318d62be7b3c903a1feb10bd8d6704.jpg" },
        { id: 5, title: "React Project", desc: "Incidunt vitae quae facere ducimus nostrum aliquid dolorum veritatis dicta!", image: "https://i.pinimg.com/236x/fc/31/8d/fc318d62be7b3c903a1feb10bd8d6704.jpg" },
    ],
    email:"Email",
    address:"Address",
    address1:"Incidunt vitae quae facere ducimus nostrum aliquid dolorum veritatis dicta!"
}